site_name: Viktor Bubanja
site_author: Viktor Bubanja
site_url: https://viktorbubanja.co

nav:
  - Blog:
    - index.md
  - About: about.md

theme:
  name: material
  palette:
    primary: black
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/anchor-solid.svg
  icon:
    logo: fontawesome/solid/anchor
  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - content.code.annotate
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select

plugins:
  - blog:
      archive: false
      blog_dir: .
      blog_toc: true
      post_url_format: "/{slug}"

social:
  - icon: fontawesome/brands/github
    link: https://github.com/Viktor-Bubanja
  - icon: fontawesome/brands/linkedin
    link: https://linkedin.com/in/Viktor-Bubanja

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/init_katex.js
  - https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@latest/dist/contrib/auto-render.min.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css
